# Device Name
substitutions:
  name: "treatlife-sl20"
  friendly_name: "Porch Light"

esphome:
  name: ${name}
  name_add_mac_suffix: true

# Device SoC
bk72xx:
  board: generic-bk7231t-qfn32-tuya

preferences:
  flash_write_interval: 1min

# Wi-Fi & AP Setup
wifi:
  ap: {}

captive_portal:

web_server:
  port: 80

# Enable Logging
logger:

# Home Assistant & OTA Keys
api:
ota:

# Reports Wi-Fi Strength in db
sensor:
- platform: wifi_signal
  name: Signal Strength
  update_interval: 60s

# Reports Device Uptime
- platform: uptime
  name: Device Uptime
  filters:
    - lambda: return x / 60.0;
  unit_of_measurement: minutes

# Factory Reset Button
button:
  - platform: factory_reset
    name: Factory Reset
    id: Reset

# Restart Switch
switch:
  - platform: restart
    name: Reboot

# Output Pins
output:
- platform: libretiny_pwm
  id: cold_white
  pin: D4
  inverted: False
  max_power: 70%
- platform: libretiny_pwm
  id: warm_white
  pin: D5
  inverted: False
  max_power: 70%

# Light Devices
light:  
- platform: cwww
  name: ${friendly_name}
  cold_white: cold_white
  warm_white: warm_white
  cold_white_color_temperature: 6500 K
  warm_white_color_temperature: 2700 K
  constant_brightness: true
  id: thelight
  restore_mode: RESTORE_DEFAULT_ON
