# Device Name
substitutions:
  name: "treatlife-sl20"
  friendly_name: "Bedroom Bulb"

# Device Config
esphome:
  name: ${name}

bk72xx:
  board: generic-bk7231t-qfn32-tuya

preferences:
  flash_write_interval: 5min

# AP & Webserver Setup
captive_portal:
wifi:
  ap: {}
  use_address: "${name}.local"

logger:
web_server:
  port: 80

# Home Assistant API & OTA
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

# Wi-Fi Strength
sensor:
- platform: wifi_signal
  name: Signal Strength
  update_interval: 60s

# Device Uptime
- platform: uptime
  name: Device Uptime
  filters:
    - lambda: return x / 60.0;
  unit_of_measurement: minutes

# Restart & Factory Reset Buttons
button:
  - platform: restart
    name: Reboot
  - platform: factory_reset
    name: Factory Reset
    id: Reset

# Output Pins
output:
- platform: libretiny_pwm
  id: cold_white
  pin: PWM2
  inverted: False
- platform: libretiny_pwm
  id: warm_white
  pin: PWM3
  inverted: False

# Light Devices
light:  
- platform: cwww
  name: ${friendly_name}
  cold_white: cold_white
  warm_white: warm_white
  cold_white_color_temperature: 6500 K
  warm_white_color_temperature: 2700 K
  constant_brightness: true
  id: thelight
  restore_mode: RESTORE_AND_ON
